/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DestinationIndexImport } from './routes/destination/index'
import { Route as DestinationMoonImport } from './routes/destination/$moon'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DestinationIndexRoute = DestinationIndexImport.update({
  path: '/destination/',
  getParentRoute: () => rootRoute,
} as any)

const DestinationMoonRoute = DestinationMoonImport.update({
  path: '/destination/$moon',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/destination/$moon': {
      preLoaderRoute: typeof DestinationMoonImport
      parentRoute: typeof rootRoute
    }
    '/destination/': {
      preLoaderRoute: typeof DestinationIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DestinationMoonRoute,
  DestinationIndexRoute,
])

/* prettier-ignore-end */
